---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-tls
  namespace: monitoring2
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICMzCCAdmgAwIBAgIUFoOZxeK+C2NCPVzK9LHlUlOtEMwwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzIzNDYwMFoXDTI2
    MTIxMzIzNDYwMFowSTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGTAXBgNVBAMTEGxvY2FsLXByb21ldGhldXMwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQJ02satmfpOrwT1obyRTaeD06mZXhtjAajV10VE8W6
    IL2w1kIDwfFbjgTybOJhjIMSKmIqYZYoFFMzvEa2FVv3o4GdMIGaMA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQU70ZI4SZhNebqkv4MNdaamuTzS3AwHwYDVR0jBBgwFoAU
    xVEkjbm47zbN2FEDsnpUre4g7IkwGwYDVR0RBBQwEoIQbG9jYWwtcHJvbWV0aGV1
    czAKBggqhkjOPQQDAgNIADBFAiEAiE3Zj/X05f5ZGA+0quip+cHP1uWMrN+dfyWQ
    XeYn/r0CIEwP/AR5m8A07Mue8FSP8PKbD+1BjcZuW4BwVTWOviPZ
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIACip3gr+gz4Iuf4fgBbsmbdsywdacAPY7q3y8pjiJuuoAoGCCqGSM49
    AwEHoUQDQgAECdNrGrZn6Tq8E9aG8kU2ng9OpmV4bYwGo1ddFRPFuiC9sNZCA8Hx
    W44E8mziYYyDEipiKmGWKBRTM7xGthVb9w==
    -----END EC PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUT5wa47qJWp5yGQ2/RSBvzWbmm/EwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MDgwMFoXDTMw
    MTIxMjE2MDgwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEgbG8c4GTt+HY3lBjoJachrA3gUA5u7ycihLD1AIo
    hJDZR3W5PfccJQ+A/LESuDKY2is05O11lBpFbbMfkqyrTKNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMVRJI25uO82zdhRA7J6
    VK3uIOyJMAoGCCqGSM49BAMCA0kAMEYCIQCSG0EntcjQnBVyjCUm058To3h4kprd
    DlyGAEPPz9qF5AIhANZfUKoAIoCOVNrds+dgo6JIstLgx125jKlVI+byujhz
    -----END CERTIFICATE-----
