apiVersion: v1
kind: Service
metadata:
  name: payment-stable
  namespace: prod
spec:
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: payment-canary
  namespace: prod
spec:
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: 5678
