---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-tls
  namespace: monitoring2
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEzCCArigAwIBAgIUPhKv7QRMCarEhb5Wd5E7tpW/UQ8wCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzIzMzIwMFoXDTI2
    MTIxMzIzMzIwMFowZTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxNTAzBgNVBAMTLHJlY2VpdmVyLXdyaXRlLm1vbml0b3Jpbmcy
    LnN2Yy5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERlZ/
    6XrjZRHebcjnredIDwcuQZqUbX0GzNhzbBIbijp5pQwKYpBbfOgdFtBD4/jRITe0
    9Z9e6j4P/vrA57mtrKOCAV8wggFbMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUB+V9
    I4r07cbkkX9MMd6GiJL1PjIwHwYDVR0jBBgwFoAUxVEkjbm47zbN2FEDsnpUre4g
    7IkwgdsGA1UdEQSB0zCB0IIscmVjZWl2ZXItd3JpdGUubW9uaXRvcmluZzIuc3Zj
    LmNsdXN0ZXIubG9jYWyGNHJlY2VpdmVyLXN0b3JlLTEubW9uaXRvcmluZzIuc3Zj
    LmNsdXN0ZXIubG9jYWw6MTA5MDeGNHJlY2VpdmVyLXN0b3JlLTIubW9uaXRvcmlu
    ZzIuc3ZjLmNsdXN0ZXIubG9jYWw6MTA5MDeGNHJlY2VpdmVyLXN0b3JlLTMubW9u
    aXRvcmluZzIuc3ZjLmNsdXN0ZXIubG9jYWw6MTA5MDcwCgYIKoZIzj0EAwIDSQAw
    RgIhAK/n8fCCmUDWp0YUAZl4jGLBesqvvmrKzS4sEuQYnQxUAiEAtkNoI998+q+C
    wiLI6h9OIiAmwKHUUT2c20B7rzA7zgw=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIDYJUVgJeK/qUH2+y2WnMkA9xWwW7vLP5ztRJo8OMKBJoAoGCCqGSM49
    AwEHoUQDQgAERlZ/6XrjZRHebcjnredIDwcuQZqUbX0GzNhzbBIbijp5pQwKYpBb
    fOgdFtBD4/jRITe09Z9e6j4P/vrA57mtrA==
    -----END EC PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUT5wa47qJWp5yGQ2/RSBvzWbmm/EwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MDgwMFoXDTMw
    MTIxMjE2MDgwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEgbG8c4GTt+HY3lBjoJachrA3gUA5u7ycihLD1AIo
    hJDZR3W5PfccJQ+A/LESuDKY2is05O11lBpFbbMfkqyrTKNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMVRJI25uO82zdhRA7J6
    VK3uIOyJMAoGCCqGSM49BAMCA0kAMEYCIQCSG0EntcjQnBVyjCUm058To3h4kprd
    DlyGAEPPz9qF5AIhANZfUKoAIoCOVNrds+dgo6JIstLgx125jKlVI+byujhz
    -----END CERTIFICATE-----
