---
# ONLY: Mutual TLS
apiVersion: v1
kind: Secret
metadata:
  name: querier-tls
  namespace: monitoring
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC7TCCApKgAwIBAgIUI0O8G/OIsCzwdxMUG00YVNg1ok8wCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MTYwMFoXDTI2
    MTIxMzE2MTYwMFowQDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxEDAOBgNVBAMTB3F1ZXJpZXIwggEiMA0GCSqGSIb3DQEBAQUA
    A4IBDwAwggEKAoIBAQDAPGbZksWsk3+hG6wXUpmtfTbqtDZx8z5eUpyBK0mp2xbN
    B4rj2IF0A8j8+3Yx+HUyer3amJA0GqM2KmU/EbIhvSLHoBRyYYnS3pK+NDrtwIej
    feWlWEAA7VI1PBWsBrqKD0sWTKnTnnnl+P/MprZLpqG5PT+sE7JpKarrKjh/0k4I
    6rWFcjBXqK+vrqZOD59WTBiTLYe6mvPY7ZArCxp9ajl5lNtnfd9a+iE8eXx4UwTr
    wi0/6J0bszlns+pFuxA/d+JY5r7Mt3LkS4GN1X8ZZ7QG5bijwoOxGouYvYcE/kcP
    Wyc4YycMLPoJIT5q22cKBWHgeOdw6A5UNWj3kIM/AgMBAAGjgZQwgZEwDgYDVR0P
    AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMB
    Af8EAjAAMB0GA1UdDgQWBBQpwtgbj0edgNZwY/eFnoBLtD4GuzAfBgNVHSMEGDAW
    gBTFUSSNubjvNs3YUQOyelSt7iDsiTASBgNVHREECzAJggdxdWVyaWVyMAoGCCqG
    SM49BAMCA0kAMEYCIQCOCR9+HA+n1RLHioAjFA0dMrbaM5sylfvDbpuhrDpS3wIh
    AI90BnctgFOcEAHlkj1oxTI9aY3nUsGYSLJyHJv8jLdk
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAwDxm2ZLFrJN/oRusF1KZrX026rQ2cfM+XlKcgStJqdsWzQeK
    49iBdAPI/Pt2Mfh1Mnq92piQNBqjNiplPxGyIb0ix6AUcmGJ0t6SvjQ67cCHo33l
    pVhAAO1SNTwVrAa6ig9LFkyp05555fj/zKa2S6ahuT0/rBOyaSmq6yo4f9JOCOq1
    hXIwV6ivr66mTg+fVkwYky2Huprz2O2QKwsafWo5eZTbZ33fWvohPHl8eFME68It
    P+idG7M5Z7PqRbsQP3fiWOa+zLdy5EuBjdV/GWe0BuW4o8KDsRqLmL2HBP5HD1sn
    OGMnDCz6CSE+attnCgVh4HjncOgOVDVo95CDPwIDAQABAoIBAAVx6iN3uRo++hdi
    oZIhi7fMLnRUbJ+RDIjlNyI55MLAyv/XGsCCy+iw1Y5ED+0Xazf/hDjyWrdKTKnG
    mddalXYuLy0cJCgfPVhxmt90IROStGTVnPd9E4cGZQgCYfmQhG0cd/uzaf+gyZwe
    Qur78XlQFXZm1tLCPHeNFhaS7uAnIX4GeJC0/GSuABab3uUMVD+RPMUNdJW1ulif
    nMcFNuqjImz7m2NRRAG/rKsugCCK1qZVnReSfEvQDRGJPHB/MrLu/knzpBLZ1od7
    O/PF7ENcB/bpgdZ4+OG60ah//QYfpzAA0SU6FE7nOBdp5wZvAsgRULOuxjiA6joe
    pGnMWiUCgYEA8TvP3jHXeAsgOVx/8YrJGZHn4MwqHMEG2RjbiYcb9btk8dHKKgU1
    7mM4m33ohbpQY4wxser66wVVfZw3TyY+fvNVyVinEUFwGBx4dKzCh7dSaEJyUlwQ
    I0u4dQUvdeePebdt9fejeZJiULIfz28UFujPvHbpeEh0E6Ces89B1S0CgYEAzADI
    yWadbELFHm82Dl+QbaW8gH+BEz3+SVexaC2/WmWyjbXvy1zP/CLsiKWDMwevlTMf
    Fuwe9gV+T2oGp+4fttTwklAmIjrSN7izbFavo7PZnppri68Hyiv4vcnCrP3XUlW7
    sLO/V4F/OeQref9YbqpqWGP997RbRo9ycmdu1ZsCgYEAjPOq2KR8xsqRcJLIu0Sh
    jkw/lY0VyilLLAynMit8vc9aAyXWn0jeI0VcbRZbh8++avweiVvIcwxx0Gw3sQqi
    l6Ds7jHbpGx858my5FGRdKU8BGlWzSK31zfGNrHp8lVz8uWn3YFtxnou8gGyLo0z
    ytMLlo5QipSjJljCgkPGrp0CgYA+Gz8Fkaf7fZhlW5Ypag6eUwbAWBEDuqvfyELK
    ZKMM8kkZu3n1f5wSNs+sCjeXIY/i7F1arSf/3kxGARFlrqkZEFrtMFlrslyteh2l
    rf5q6CYokvqK3A6TDi/8F6Cc6erTtiYd9ZsbGOGSzlQuH/7cMiWOI2L+NnpTUPiW
    u8aSYQKBgGcFHsvCCg9E767/cBN6uk4XpFQ37qxnt0lEr4jMJq5HchJQUjX/zsx/
    m6SavukkvmiLl1xE1jbgQiUh10gH5MTMOxUKw8IfxdoT9/CR0IFJDEud+uDm4nou
    IIbJ5GAZLj5YlMqP1HGXrnEiA2dx7hM5JobfAg1JEluDzbPkq3u8
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUT5wa47qJWp5yGQ2/RSBvzWbmm/EwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MDgwMFoXDTMw
    MTIxMjE2MDgwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEgbG8c4GTt+HY3lBjoJachrA3gUA5u7ycihLD1AIo
    hJDZR3W5PfccJQ+A/LESuDKY2is05O11lBpFbbMfkqyrTKNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMVRJI25uO82zdhRA7J6
    VK3uIOyJMAoGCCqGSM49BAMCA0kAMEYCIQCSG0EntcjQnBVyjCUm058To3h4kprd
    DlyGAEPPz9qF5AIhANZfUKoAIoCOVNrds+dgo6JIstLgx125jKlVI+byujhz
    -----END CERTIFICATE-----
