---
# ONLY: Mutual TLS
apiVersion: v1
kind: Secret
metadata:
  name: storegateway-tls
  namespace: monitoring
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMDCCAtagAwIBAgIUJOdKwWhoDbB5+Yoc/zuPd5mu3QcwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MTgwMFoXDTI2
    MTIxMzE2MTgwMFowYjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxMjAwBgNVBAMTKXN0b3JlZ2F0ZXdheS5tb25pdG9yaW5nLnN2
    Yy5jbHVzdGVyLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    saEGUuD9fFmdqy3+0CFcUXIfZwHaUQD60taZrxoJXlIDDGHlVeT9GMANf/SqdjPP
    ebj9lHsJfR2uu5r8sy824HB721HUJ7/lEXdQ2YA17gASwkfug28gBnuxfcfWoH7N
    c6xMZxqPNFXO1Uw/d90cnrwbt+W6u0NttPF2zLVnB4WMaNZpNqWpf3HafTe6Og4m
    CISMIzF1t6OuaAY0Gtq1ZNWg1Np+CuJ8hkwVeGdJWP0LlcUlt3/AnnV6u2j0hYns
    /S9zhqZmmPsZYaXQ1AH+aHUZOi9GRi9LLhv3+QAT05yooxQxKf47xYn72CnOPWYO
    BYTNTLswkHpf0xqOmqLh8wIDAQABo4G2MIGzMA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQU+iNrcwlsdufgSbp9PMSXV0GE9wQwHwYDVR0jBBgwFoAUxVEkjbm47zbN2FED
    snpUre4g7IkwNAYDVR0RBC0wK4Ipc3RvcmVnYXRld2F5Lm1vbml0b3Jpbmcuc3Zj
    LmNsdXN0ZXIubG9jYWwwCgYIKoZIzj0EAwIDSAAwRQIhAPcu7o8ABss0QCvpF3nD
    nU4sIY9QpmBavXXWQJRSY5/jAiByZsXlx5K6fMFURbMLtipC/e90Pnx2MUCwvfIK
    LZFoTA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAsaEGUuD9fFmdqy3+0CFcUXIfZwHaUQD60taZrxoJXlIDDGHl
    VeT9GMANf/SqdjPPebj9lHsJfR2uu5r8sy824HB721HUJ7/lEXdQ2YA17gASwkfu
    g28gBnuxfcfWoH7Nc6xMZxqPNFXO1Uw/d90cnrwbt+W6u0NttPF2zLVnB4WMaNZp
    NqWpf3HafTe6Og4mCISMIzF1t6OuaAY0Gtq1ZNWg1Np+CuJ8hkwVeGdJWP0LlcUl
    t3/AnnV6u2j0hYns/S9zhqZmmPsZYaXQ1AH+aHUZOi9GRi9LLhv3+QAT05yooxQx
    Kf47xYn72CnOPWYOBYTNTLswkHpf0xqOmqLh8wIDAQABAoIBAA6VEPpvoz+4vhUW
    GV70YV2diDuiAk5q5yyB457Lycyz4BfKVzp3w9nRTz2bupbDmbSWqqXfrlK89uHk
    Ty4iofDg9+1BLxdbgJTjfhngL0BsdYQvklwfgyCLhqTnaZSsp3Wa+OOJ+z52Dbaj
    CmuiFYrOfic/Twodw5bg/KDBNhKyEYGA3X1g6OzV4AivR10b3bDyFffumRKw7bYZ
    fWbQuxlzALJTDjd+/wr7OcHYyHlG25ZBy4BR9uyA5YB31REDd5mIz/r61HUoHsEC
    XxHF4qJxHrCtfJSp7lV22HwesAqKWunsCMROGdkMAA4krFm4RQxjicEgFVB2Z7ud
    QDMPQ6ECgYEA5YecowBLo38C8BOMtEiulvop9OPjMb5i4jf4EzZgweqYMpBqqV3m
    RAbTJlogMyKFAU0lKJWdn5DaEDRHDRy+LFcCV+29AQpgR2qlYaPzk+RHgWhNLfP/
    TRQHAio2KhDDUN6RLIF5exeX59uyeXkc+DxWc7zbeiOxb6l61wBNU4MCgYEAxh0m
    09ZyFd47PQucw/AYv1ni7S3m4R9xN4CmOVDmTv9XNCKgn795lTKw5xyO3PC8dbpF
    Ns49ovBcwCOL9SE59gbB3zAPTuPCIvZKoTfLl3wSgz7dpeh0igV4axH3U75gYKvZ
    CsBrpCRw9H1b/HISk6pqTkNXZe2ykyrrPQ4lPNECgYEAqteBkyHJKuyCt0cV16qx
    qNaTHB/zHzdiSpb2Iva6lhuTJS+w9Fdb6Q5bY5R5mxX6gbl2Cvsx027xoFYI/I2E
    T2SD7gaaQ4gBmaabak2qI04qmvuTVrziLfDWNppMrorDlhHTZJkKXsB05LL16Mxo
    76uZfZP4mLSwgThYomcrJxkCgYAl/gEsLrvCJdQGaOuvR6P3Ti2OfncARR9ZHXrD
    ExiXnbADd4CGIhoW2pnCOF/NTv1VNlt/nx2C2cVvs2FrqOuMms8jFfxZjKP2QHUf
    ZavNaSXDtZKb9nAi59mn7tIXZTLmVw5QWYZK/BINUN0LFHUrjErGp3NjQKo2PszN
    8KCDgQKBgECgG9f5oNnN6lLrCeBxm+Jeli/lv4Cnp3fLfm5fRy5F3kI6tzNKsE9x
    4mKapTjGa3gpcHfi+hJpdu8IXTMuQc5SK616hmvaJl0msZ9M3o36UTk2yH8p9/g5
    1dSb0jgD+64Q9jrr8Vpb05bL/7GXu+PCH3EGVsAP6E/XzcGhhoH6
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2TCCAX6gAwIBAgIUT5wa47qJWp5yGQ2/RSBvzWbmm/EwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTI1MTIxMzE2MDgwMFoXDTMw
    MTIxMjE2MDgwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEgbG8c4GTt+HY3lBjoJachrA3gUA5u7ycihLD1AIo
    hJDZR3W5PfccJQ+A/LESuDKY2is05O11lBpFbbMfkqyrTKNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMVRJI25uO82zdhRA7J6
    VK3uIOyJMAoGCCqGSM49BAMCA0kAMEYCIQCSG0EntcjQnBVyjCUm058To3h4kprd
    DlyGAEPPz9qF5AIhANZfUKoAIoCOVNrds+dgo6JIstLgx125jKlVI+byujhz
    -----END CERTIFICATE-----
